#!/bin/bash

case "$1" in 
start)
   node /opt/honkbot/honkbot.js &
   echo $!>/var/run/honkbot.pid
   ;;
stop)
   kill `cat /var/run/honkbot.pid`
   rm /var/run/honkbot.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/honkbot.pid ]; then
      echo honkbot is running, pid=`cat /var/run/honkbot.pid`
   else
      echo honkbot is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0